baseurl = "https://www.zint-it.de/" # Hostname (and path) to the root.
title = "Jonatan Zint" # Site title.
theme = "hugo-coder"
languagecode = "de"
defaultcontentlanguage = "de"


[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  langseparator = "|" # separates menus from language selectors.
  author = "Jonatan Zint" # Author's name.
  info = "Softwareberatung und IT Projekte" # Author's job title or info.
  description = "Jonatan Zint Softwareberatung und IT Projekte" # Site description.
  keywords = "blog,developer,personal" # Site keywords.
  avatarURL = "img/author.png" # Contain the path of the optionnal avatar in the static folder.
  hideCredits = true
  hideCopyright = true


  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2011

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/l0rn/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/jonatan-zint-231447152/"

[languages]
    [languages.de]
        languagename = "Deutsch" # The language name to be displayed in the selector.
        title = "Jonatan Zint"

        # You can configure the theme parameter for each language.
        [languages.de.params]
        author = "Jonatan Zint"
        info = "Softwareberatung und IT Projekte"
        description = "Jonatan Zint's persönliche Webseite"
        keywords = "blog,softwareentwicklung,beratung,it"



    [languages.en]
        languagename = "English"
        title = "Jonatan Zint"

        [languages.en.params]
            author = "Jonatan Zint"
            info = "Software consultung and IT projects"
            description = "Software consultung and IT projects"
            keywords = "blog,developer,personal,software consulting"